apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    purpose: helm-service 
    project: roboshop
spec:
  selector:
    purpose: helm-practice
    project: roboshop
  ports:
    - protocol: TCP
      port: {{ .values.service.port }} # service port
      targetPort: 80 # app/container port
